autogen: update common files

diff --git a/.github/workflows/umino-project.yml b/.github/workflows/umino-project.yml
--- a/.github/workflows/umino-project.yml
+++ b/.github/workflows/umino-project.yml
@@ -4,131 +4,95 @@ on:
     types:
       - opened
       - reopened
-      - closed
       - assigned
       - unassigned
       - labeled
-      - unlabeled
-      - edited
   pull_request:
     types:
       - opened
       - reopened
       - review_requested
-      - closed
       - assigned
       - unassigned
       - labeled
-      - unlabeled
-      - edited
-  issue_comment:
-    types:
-      - created
 
 env:
-  backlog: To do in this week
-  inbox: Inbox
+  unread: Unread
   in_progress: In Progress
-  in_waiting: In Waiting
   gh_project_token: ${{ secrets.GH_TOKEN }}
   user: HiromiShikata
   project_id: 48
+  project_v2_id: PVT_kwHOAGJHa84AFWnr
+  field_id: PVTF_lAHOAGJHa84AFWnrzgIk_H0
 
 jobs:
-  opened_or_reopened:
+  umino-job:
     name: opened_or_reopened
     runs-on: ubuntu-latest
-    if: github.event.action == 'opened' || github.event.action == 'reopened'
+    if: >-
+      (github.event_name == 'issues' && github.event.issue.state == 'open') || 
+      (github.event_name == 'pull_request' && github.event.pull_request.state == 'open') &&
+      (github.event.action == 'opened' || github.event.action == 'reopened' || 
+      github.event.action == 'assigned' || github.event.action == 'unassigned' ||
+      (github.event.action == 'labeled' && github.event.label.name == 'hiromishikata:task:offline'))
     steps:
-      - name: Move issue to ${{ env.inbox }}
-        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
+      - name: Move issue to ${{ env.unread }}
+        uses: leonsteinhaeuser/project-beta-automations@v2.2.1
         with:
           gh_token: ${{ env.gh_project_token }}
           user: ${{ env.user }}
           project_id: ${{ env.project_id }}
           resource_node_id: ${{ github.event.pull_request.node_id || github.event.issue.node_id }}
-          status_value: ${{ env.inbox }}
-  assigned_or_unassigned:
-    name: assigned_or_unassigned
-    runs-on: ubuntu-latest
-    if: github.event.action == 'assigned' || github.event.action == 'unassigned'
-    steps:
-      - name: Move issue to ${{ env.inbox }}
-        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
+          status_value: ${{ env.unread }}
+      - name: Comment #offline
+        if: github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'hiromishikata:task:offline'
+        uses: actions/github-script@v7
         with:
-          gh_token: ${{ env.gh_project_token }}
-          user: ${{ env.user }}
-          project_id: ${{ env.project_id }}
-          resource_node_id: ${{ github.event.pull_request.node_id || github.event.issue.node_id }}
-          status_value: ${{ env.inbox }}
-      - uses: actions-ecosystem/action-remove-labels@v1
-        with:
-          labels: working right now
+          github-token: ${{secrets.GITHUB_TOKEN}}
+          script: |
+            const issueComment = {
+              owner: context.repo.owner,
+              repo: context.repo.repo,
+              issue_number: context.issue.number,
+              body: '#offline'
+            };
+            github.issues.createComment(issueComment);
 
-  labeled_working:
-    runs-on: ubuntu-latest
-    if: github.event.action == 'labeled' && github.event.label.name == 'working right now'
-    steps:
-      - name: Move issue to ${{ env.in_progress }}
-        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
-        with:
-          gh_token: ${{ env.gh_project_token }}
-          user: ${{ env.user }}
-          project_id: ${{ env.project_id }}
-          resource_node_id: ${{ github.event.pull_request.node_id || github.event.issue.node_id }}
-          status_value: ${{ env.in_progress }}
-  unlabeled_working:
-    runs-on: ubuntu-latest
-    if: github.event.action == 'unlabeled' && github.event.label.name == 'working right now'
-    steps:
-      - name: Move issue to ${{ env.inbox }}
-        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
-        with:
-          gh_token: ${{ env.gh_project_token }}
-          user: ${{ env.user }}
-          project_id: ${{ env.project_id }}
-          resource_node_id: ${{ github.event.pull_request.node_id || github.event.issue.node_id }}
-          status_value: ${{ env.inbox }}
-  labeled_will_close:
-    runs-on: ubuntu-latest
-    if: github.event.action == 'labeled' && github.event.label.name == 'will close automatically by PR'
-    steps:
-      - name: Move issue to ${{ env.in_waiting }}
-        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
-        with:
-          gh_token: ${{ env.gh_project_token }}
-          user: ${{ env.user }}
-          project_id: ${{ env.project_id }}
-          resource_node_id: ${{ github.event.pull_request.node_id || github.event.issue.node_id }}
-          status_value: ${{ env.in_waiting }}
-  edited_title_for_waiting:
-    runs-on: ubuntu-latest
-    if: github.event.action == 'edited' && (startsWith(github.event.issue.title, 'Waiting for ') || startsWith(github.event.pull_request.title, 'Waiting for '))
-    steps:
-      - name: Move issue to ${{ env.in_waiting }}
-        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
-        with:
-          gh_token: ${{ env.gh_project_token }}
-          user: ${{ env.user }}
-          project_id: ${{ env.project_id }}
-          resource_node_id: ${{ github.event.pull_request.node_id || github.event.issue.node_id }}
-          status_value: ${{ env.in_waiting }}
+      - run: |
+          OWNER=$(echo ${{ github.repository }} | cut -d '/' -f 1)
+          REPO=$(echo ${{ github.repository }} | cut -d '/' -f 2)
+          ENTITY_TYPE=$(echo ${{ github.event_name }} | grep -q "pull_request" && echo "pullRequest" || echo "issue")
+          NUMBER=$(echo ${{ github.event_name }} | grep -q "pull_request" && echo ${{ github.event.pull_request.number }} || echo ${{ github.event.issue.number }})
 
-  comment-command:
-    runs-on: ubuntu-latest
-    steps:
-      - if: |
-          github.event.action == 'created'
-          && startsWith(github.event.comment.body, '#take')
-        run: |
-          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" -d '{"assignees": ["${{ github.event.comment.user.login }}"]}' https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees
-      - if: |
-          github.event.action == 'created'
-          && startsWith(github.event.comment.body, '#close')
-        run: |
-          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" -X PATCH -d '{"state": "closed"}' https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
-      - if: |
-          github.event.action == 'created'
-          && startsWith(github.event.comment.body, '#offline')
-        run: |
-          curl -H "Authorization: token ${{ secrets.GH_TOKEN }}" -X PATCH -d '{"labels": ["hiromishikata:task:offline"]}' https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}
+          QUERY_DATA='{ "query": "query { repository(owner: \"'$OWNER'\", name: \"'$REPO'\") { '${ENTITY_TYPE}'(number: '$NUMBER') { projectItems(first: 10) { nodes { id } } } } }" }'
+          RESPONSE=$(curl -X POST -H "Authorization: bearer ${{ secrets.GH_TOKEN }}" -H "Content-Type: application/json" --data "$QUERY_DATA" https://api.github.com/graphql)
+
+          if echo $RESPONSE | grep -q "errors"; then
+            echo "Error in GraphQL query"
+            echo "GraphQL Response: $RESPONSE"
+            exit 1
+          fi
+
+          if [ "$ENTITY_TYPE" = "pullRequest" ]; then
+            ITEM_ID=$(echo $RESPONSE | jq -r '.data.repository.pullRequest.projectItems.nodes[0].id')
+          else
+            ITEM_ID=$(echo $RESPONSE | jq -r '.data.repository.issue.projectItems.nodes[0].id')
+          fi
+
+          if [ "$ITEM_ID" = "null" ] || [ -z "$ITEM_ID" ]; then
+            echo "No valid item ID found, cannot proceed"
+            exit 1
+          fi
+
+          CLEAR_FIELD_DATA="{\"query\":\"mutation { clearProjectV2ItemFieldValue(input: {projectId: \\\"${{ env.project_v2_id }}\\\", fieldId: \\\"${{ env.field_id }}\\\", itemId: \\\"$ITEM_ID\\\"}) { clientMutationId }}\"}"
+          CLEAR_RESPONSE=$(curl --request POST \
+            --url https://api.github.com/graphql \
+            --header "Authorization: Bearer ${{ env.gh_project_token }}" \
+            --header "Content-Type: application/json" \
+            --data "$CLEAR_FIELD_DATA")
+
+          if echo $CLEAR_RESPONSE | grep -q "errors"; then
+            echo "Error in clearing field"
+            echo "Clear Field Response: $CLEAR_RESPONSE"
+            exit 1
+          fi
